Allows updating the project to VS 2013
Without this line, std::shared_ptr will not be found when project is
upgraded to VS 2013.
Error 1 error C2039: 'shared_ptr' : is not a member of 'std'

The project can still be built in VS 2010 or VS 2012 with the new
include.